/**:
  ros__parameters:
    video_device: /dev/video0
    framerate: 30.0
    frame_id: front_camera_optical_frame
    image_width: 640
    image_height: 480
    camera_name: front_camera
    image_topic: /front_camera/image_raw
    camera_info_topic: /front_camera/camera_info
    camera_info_url: package://cobot1/config/front_camera_info.yaml

    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
    exposure: -1
    focus: -1
